// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tqrnhqrdtygxuotenxwr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRxcm5ocXJkdHlneHVvdGVueHdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3NzM0NDAsImV4cCI6MjA3MTM0OTQ0MH0.mGZz8JgIGb54721WyRQi7JAUnnXWfgTyUXgUxDAr3Pg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});